# dotangad's Alacritty config 

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '0x0F1419'
    foreground: '0xB3B1AD'

  # Normal colors
  normal:
    black: '0x01060E'
    red: '0xEA6C73'
    green: '0x91B362'
    yellow: '0xF9AF4F'
    blue: '0x53BDFA'
    magenta: '0xFAE994'
    cyan: '0x90E1C6'
    white: '0xC7C7C7'

  # Bright colors
  bright:
    black: '0x686868'
    red: '0xF07178'
    green: '0xC2D94C'
    yellow: '0xFFB454'
    blue: '0x59C2FF'
    magenta: '0xFFEE99'
    cyan: '0x95E6CB'
    white: '0xFFFFFF'

font:
  size: 14

  normal:
    family: 'Fantasque Sans Mono'
    style: Regular
  bold:
    family: 'Fantasque Sans Mono'
    style: Bold
  italics:
    family: 'Fantasque Sans Mono'
    style: Italic

  offset:
    x: 0
    y: 0

window:
  title: 'dotangad @ macbook'
  decorations: none
  padding:
    y: 0
    x: 0

cursor:
  style: Block

key_bindings:
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
  - { key: Space,     mods: Alt,          chars: " "                     }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # one word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # one word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: F,    mods: Command, action: ToggleFullscreen } # enter fullscreen

