# dotangad's Alacritty config 

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

font:
  size: 14

  normal:
    family: 'Fantasque Sans Mono'
    style: Regular
  bold:
    family: 'Fantasque Sans Mono'
    style: Bold
  italics:
    family: 'Fantasque Sans Mono'
    style: Italic

  offset:
    x: 0
    y: 0

window:
  title: 'dotangad @ macbook'
  decorations: none
  padding:
    y: 0
    x: 0

cursor:
  style: Block

key_bindings:
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
  - { key: Space,     mods: Alt,          chars: " "                     }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: F,    mods: Command, action: ToggleFullscreen } # enter fullscreen

