alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias g='hub'
alias la="ls -la"
alias rc="source $HOME/.zshrc"
alias td=todolist
alias startApache='/Applications/MAMP/bin/startApache.sh'
alias stopApache='/Applications/MAMP/bin/stopApache.sh'
alias startMysql='/Applications/MAMP/bin/startMysql.sh'
alias stopMysql='/Applications/MAMP/bin/stopMysql.sh'
alias gohome='cd /Users/dotangad/code/go/src/github.com/dotangad/'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
